# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 70b1072425695079d8c7e5dae518fc6f2d31d8d69a57640e964aca93701e4deb09f7586ec00dc9bc6ac1c0df36575db3e2316cb4b2d7022416b2c83f7d774de8

test:
  secret_key_base: 1dc4183b56af11288371252fb5f62bf1918602e98551a2b2010b9086c1bf24437e60f739866e10505660fa0372b706d4180c7c0e82efdfd35f667780af65a76b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
